spring:
  config:
    activate:
      on-profile: dev

  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/notice_board
#    url: jdbc:log4jdbc:mysql://106.255.230.162:46070/singles_kokoa_v4?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: chs
    password: javajava
    hikari:
        connection-timeout: 30000
        maximum-pool-size: 10
        #      idle-timeout: 60000
        minimum-idle: 10

custom:
  logFilePath: /Users/chs/정리/logDir/logWriter.txt
